enum Packets {
    LOGIN_PACKET = 0x01,
    PLAY_STATUS_PACKET = 0x02,
    SERVER_TO_CLIENT_HANDSHAKE_PACKET = 0x03,
    CLIENT_TO_SERVER_HANDSHAKE_PACKET = 0x04,
    DISCONNECT_PACKET = 0x05
}

export default Packets